CREATE SCHEMA app;
GO
CREATE TABLE app.[User]
(
    userId UNIQUEIDENTIFIER PRIMARY KEY,
    username NVARCHAR(50) NOT NULL,
    email NVARCHAR(50) NOT NULL UNIQUE,
    worldAnvilUsername NVARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE app.[WASnippet]
(
    snippetId UNIQUEIDENTIFIER PRIMARY KEY,
    userId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES app.[User](userId) NOT NULL,
    worldAnvilArticleId UNIQUEIDENTIFIER NOT NULL,
    title NVARCHAR(50) NOT NULL,
    content NVARCHAR(MAX) NOT NULL
);
CREATE TABLE app.[WACharacterSet]
(
    characterSetId UNIQUEIDENTIFIER PRIMARY KEY,
    userId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES app.[User](userId) NOT NULL,
    characterSet NVARCHAR(MAX) NOT NULL
);
CREATE TABLE app.[WAEmbedding]
(
    embeddingId UNIQUEIDENTIFIER PRIMARY KEY,
    characterSetId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES app.[WACharacterSet](characterSetId) NOT NULL,
    vector VARBINARY(MAX) NOT NULL
);
